cache:
  image: redis

db:
  image: postgres

search:
  image: elasticsearch

web:
  build: .
  ports:
    - "8000:8000"
  links:
    - cache
    - db
    - search
  command: ./manage.py runserver 0.0.0.0:8000
